### ISSUE TITLE
Nuevo botón de Multijugador local (O algo similar)

### ISSUE THREAD

**Issue by SOSandreu1095** [SOSandreu1095/retrorace#41]
Ahora que el juego lo permite.... estaría bien llevar a cabo un nuevo botón que permita jugar modo duo con otra persona

Por lo que quedarían 4 botones:
 - Individual
 - Duo
 - Online
 - Ranking

O algo similar

En el Individual solo con crear la partida se crea un personaje, asi que no es necesario agregar mas

En el duo, antes de hacer un partida.start()... habria que añadirle 1 personaje más

**Comment by Monxus** [comment]
Implementado, funcionando y subido a mi branch.
